
properties([
    parameters([
        booleanParam(name: 'Refresh', defaultValue: false, description: 'Read Jenkinsfile and exit.'),
    ])
])

pipeline{
    agent any
    stages{
        stage('Refresh Jenkins File'){
            when{
                expression{
                    return params.Refresh == true
                }
            }
            steps{
                script{
                    echo "This is the Jenkins Script from MPS job"
                }
            }
        }

        stage('Excute the tests'){
            steps{
                echo "Execute tests block is being executed"
            }
        }
    }

}