properties([
    parameters([
        booleanParam(name: 'Refresh', defaultValue: false, description: 'Read Jenkinsfile and exit.'),
    ])
])

pipeline{
    // agent any
    agent{ dockerfile true
        // dockerfile{
        //     filename 'Jenkins/Dockerfile'
        // }
    }
    // environment {
    //     PATH = "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin/docker"
    // }
    
    stages{
        stage('Check Docker Version'){
            steps{
                sh 'docker --version'
            }
        }

        stage('Refresh Jenkins File'){
            when{
                expression{
                    return params.Refresh == true
                }
            }
            steps{
                script{
                    echo "This is the Jenkins Script from MPS job"
                }
            }
        }

        stage('Excute the tests'){
            steps{
                echo "Execute tests block is being executed"
            }
        }
    }

}